# Generated by Django 6.0.3 on 2026-03-26 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('digital_id', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('account_claimed', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('traditional_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_residence', models.CharField(blank=True, max_length=200, null=True)),
                ('close_relative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('close_relative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('close_relative_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('managing_organization_id', models.UUIDField(blank=True, null=True)),
                ('managing_organization_display', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_by_staff_id', models.UUIDField(blank=True, null=True)),
                ('registered_by_staff_display', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='PatientOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient OTP',
                'verbose_name_plural': 'Patient OTPs',
                'db_table': 'patient_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='patients_full_na_4556a3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patients_phone_n_eba9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['registration_date'], name='patients_registr_b6f350_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='patients_nationa_c07601_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['digital_id'], name='patients_digital_986407_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['managing_organization_id'], name='patients_managin_2a4875_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['registered_by_staff_id'], name='patients_registe_ce6843_idx'),
        ),
    ]
