# Generated by Django 6.0.3 on 2026-04-09 19:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.CharField(db_index=True, editable=False, help_text='Human-readable ID — auto-generated as ENC-{NNNN}', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='finished', max_length=20)),
                ('encounter_class', models.CharField(choices=[('AMB', 'Ambulatory (OPD)'), ('EMER', 'Emergency'), ('IMP', 'Inpatient'), ('SS', 'Short Stay')], default='AMB', max_length=10)),
                ('visit_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('symptoms', models.TextField(blank=True, help_text='Chief complaint / presenting symptoms', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Working / final diagnosis', null=True)),
                ('notes', models.TextField(blank=True, help_text='Clinician notes', null=True)),
                ('clinician_id', models.UUIDField(db_index=True, help_text='UUID of the HealthProfessional in HMS')),
                ('clinician_display', models.CharField(help_text='Cached full name of the clinician at time of encounter', max_length=255)),
                ('organization_id', models.UUIDField(db_index=True, help_text='UUID of the Hospital (Organization) in HMS')),
                ('organization_display', models.CharField(help_text='Cached hospital name at time of encounter', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Encounter',
                'verbose_name_plural': 'Encounters',
                'db_table': 'encounters',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_id', models.CharField(db_index=True, editable=False, help_text='Human-readable ID — auto-generated as PRESC-{YYYY}-{NNNN}', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on-hold', 'On Hold')], db_index=True, default='active', max_length=20)),
                ('intent', models.CharField(choices=[('proposal', 'Proposal'), ('plan', 'Plan'), ('order', 'Order')], default='order', max_length=20)),
                ('prescription_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescribed_by_id', models.UUIDField(db_index=True)),
                ('prescribed_by_display', models.CharField(max_length=255)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('organization_display', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_requests', to='patients.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_requests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Medication Request',
                'verbose_name_plural': 'Medication Requests',
                'db_table': 'medication_requests',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDispense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(db_index=True, help_text='Medication name e.g. Amoxicillin 500mg', max_length=255)),
                ('status', models.CharField(choices=[('preparation', 'Preparation'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='completed', max_length=20)),
                ('dosage_morning', models.PositiveSmallIntegerField(default=0, help_text='Tablets in the morning')),
                ('dosage_afternoon', models.PositiveSmallIntegerField(default=0, help_text='Tablets in the afternoon')),
                ('dosage_evening', models.PositiveSmallIntegerField(default=0, help_text='Tablets in the evening')),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, help_text='Number of days to take the medication', null=True)),
                ('meal_timing', models.CharField(choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('with_meal', 'With Meal'), ('anytime', 'Anytime (empty stomach OK)')], default='anytime', max_length=20)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('dispensed_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('dispensed_by_display', models.CharField(blank=True, max_length=255, null=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='patients.medicationrequest')),
            ],
            options={
                'verbose_name': 'Medication Dispense',
                'verbose_name_plural': 'Medication Dispenses',
                'db_table': 'medication_dispenses',
                'ordering': ['medication_request', 'drug_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_request_id', models.CharField(db_index=True, editable=False, help_text='Human-readable ID — auto-generated as LAB-{NNNN}', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('category', models.CharField(choices=[('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('pathology', 'Pathology'), ('other', 'Other')], db_index=True, default='laboratory', max_length=30)),
                ('test_type', models.CharField(db_index=True, help_text='e.g. Blood Count, Urinalysis, X-Ray', max_length=255)),
                ('request_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Clinical reason / instructions for the lab', null=True)),
                ('ordered_by_id', models.UUIDField(db_index=True, help_text='UUID of the requesting HealthProfessional in HMS')),
                ('ordered_by_display', models.CharField(max_length=255)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('organization_display', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='patients.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('partial', 'Partial'), ('final', 'Final'), ('amended', 'Amended'), ('cancelled', 'Cancelled')], db_index=True, default='final', max_length=20)),
                ('issued', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('interpretation', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical'), ('pending', 'Pending')], db_index=True, default='pending', help_text='Overall interpretation of the report', max_length=20)),
                ('conclusion', models.TextField(blank=True, help_text='Narrative summary of findings', null=True)),
                ('performer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('performer_display', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.OneToOneField(help_text='The ServiceRequest this report answers', on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_report', to='patients.servicerequest')),
            ],
            options={
                'verbose_name': 'Diagnostic Report',
                'verbose_name_plural': 'Diagnostic Reports',
                'db_table': 'diagnostic_reports',
                'ordering': ['-issued'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('loinc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('value_string', models.CharField(blank=True, help_text='Free-text result (Positive / Negative / …)', max_length=255, null=True)),
                ('value_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Numeric result value', max_digits=12, null=True)),
                ('value_unit', models.CharField(blank=True, help_text='Unit e.g. g/dL, mmol/L', max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, help_text='e.g. 12–16 g/dL', max_length=100, null=True)),
                ('interpretation', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical'), ('pending', 'Pending')], default='normal', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.diagnosticreport')),
            ],
            options={
                'verbose_name': 'Diagnostic Observation',
                'verbose_name_plural': 'Diagnostic Observations',
                'db_table': 'diagnostic_observations',
                'ordering': ['test_name'],
                'indexes': [models.Index(fields=['report'], name='diagnostic__report__bdef41_idx'), models.Index(fields=['test_name'], name='diagnostic__test_na_708af9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient'], name='encounters_patient_42ac76_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['visit_date'], name='encounters_visit_d_8bac55_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['clinician_id'], name='encounters_clinici_a0fb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['organization_id'], name='encounters_organiz_b6ff0b_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='encounters_status_2bbb51_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrequest',
            index=models.Index(fields=['patient'], name='medication__patient_648ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrequest',
            index=models.Index(fields=['encounter'], name='medication__encount_4fb0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrequest',
            index=models.Index(fields=['prescription_date'], name='medication__prescri_72ee30_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrequest',
            index=models.Index(fields=['prescribed_by_id'], name='medication__prescri_914e88_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrequest',
            index=models.Index(fields=['organization_id'], name='medication__organiz_5aa436_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrequest',
            index=models.Index(fields=['status'], name='medication__status_6cd68d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['medication_request'], name='medication__medicat_a00165_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['drug_name'], name='medication__drug_na_e4bc67_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['dispensed_by_id'], name='medication__dispens_951f35_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['status'], name='medication__status_94ac2a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['patient'], name='service_req_patient_e63c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['encounter'], name='service_req_encount_7b26df_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['request_date'], name='service_req_request_6943f2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['ordered_by_id'], name='service_req_ordered_f85506_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization_id'], name='service_req_organiz_8ab599_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='service_req_status_ba17eb_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['service_request'], name='diagnostic__service_cc2cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['issued'], name='diagnostic__issued_265069_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['status'], name='diagnostic__status_b6fea8_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['interpretation'], name='diagnostic__interpr_014e63_idx'),
        ),
    ]
