# Generated by Django 6.0.3 on 2026-04-09 22:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_encounter_medicationrequest_medicationdispense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='booked', max_length=32)),
                ('appointment_type_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('appointment_type_display', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('practitioner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('practitioner_display', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('location_display', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-start', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'start'], name='appointment_patient_18d305_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx'), models.Index(fields=['appointment_type_code'], name='appointment_appoint_4d882e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='final', max_length=32)),
                ('test_code', models.CharField(db_index=True, max_length=100)),
                ('test_display', models.CharField(max_length=255)),
                ('effective_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('result_value', models.CharField(blank=True, max_length=255, null=True)),
                ('performer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('performer_display', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_tests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Diagnostic Test',
                'verbose_name_plural': 'Diagnostic Tests',
                'db_table': 'diagnostic_tests',
                'ordering': ['-effective_datetime', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'effective_datetime'], name='diagnostic__patient_183205_idx'), models.Index(fields=['status'], name='diagnostic__status_d08a9e_idx'), models.Index(fields=['test_code'], name='diagnostic__test_co_34815d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='completed', max_length=32)),
                ('vaccine_code', models.CharField(db_index=True, max_length=100)),
                ('vaccine_display', models.CharField(max_length=255)),
                ('occurrence_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('performer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('performer_display', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=80, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'db_table': 'vaccinations',
                'ordering': ['-occurrence_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'occurrence_date'], name='vaccination_patient_4196a2_idx'), models.Index(fields=['status'], name='vaccination_status_0b887f_idx'), models.Index(fields=['vaccine_code'], name='vaccination_vaccine_51c28d_idx')],
            },
        ),
    ]
