# Generated by Django 6.0.3 on 2026-04-09 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_diagnostictest_vaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='final', max_length=32)),
                ('category_code', models.CharField(blank=True, max_length=64, null=True)),
                ('category_display', models.CharField(blank=True, max_length=100, null=True)),
                ('observation_code', models.CharField(db_index=True, max_length=100)),
                ('observation_display', models.CharField(max_length=255)),
                ('effective_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('value_quantity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_quantity_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('value_quantity_system', models.CharField(blank=True, max_length=255, null=True)),
                ('value_quantity_code', models.CharField(blank=True, max_length=64, null=True)),
                ('interpretation_code', models.CharField(blank=True, max_length=64, null=True)),
                ('interpretation_display', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'db_table': 'observations',
                'ordering': ['-effective_datetime', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'effective_datetime'], name='observation_patient_8a4cdb_idx'), models.Index(fields=['status'], name='observation_status_268248_idx'), models.Index(fields=['observation_code'], name='observation_observa_164715_idx')],
            },
        ),
    ]
